---

platform: resolver

vpc_lookup:
  default: dev

dyn_vpc_lookup: "{{vpc_lookup['env']|default(vpc_lookup['default'])}}"

service:
  dns:
    disk_size:
      default: 10
    port_exposed:
      default: 53
    port_protocol:
      default: udp

dyn_role_disk_size:     "{{service[ec2_role]['disk_size'][env]|default(service[ec2_role]['disk_size']['default'])}}"
dyn_role_port_exposed:  "{{service[ec2_role]['port_exposed'][env]|default(service[ec2_role]['port_exposed']['default'])}}"
dyn_role_port_protocol: "{{service[ec2_role]['port_protocol'][env]|default(service[ec2_role]['port_protocol']['default'])}}"
